export const ADD_TO_MY_FAVOURITE_SUCCESS = "ADD_TO_MY_FAVOURITE_SUCCESS";
export const ADD_TO_MY_FAVOURITE_FAIL = "ADD_TO_MY_FAVOURITE_FAIL";
export const REMOVE_FROM_MY_FAVOURITE = "REMOVE_FROM_MY_FAVOURITE";

export const FAVOURITE_LIST_MY_REQUEST = "FAVOURITE_LIST_MY_REQUEST";
export const FAVOURITE_LIST_MY_SUCCESS = "FAVOURITE_LIST_MY_SUCCESS";
export const FAVOURITE_LIST_MY_FAIL = "FAVOURITE_LIST_MY_FAIL";
